Gentoo Linux Hybrid ISO boot options - [F1 to display available kernels]

Please hit F1 to see the available kernels on this livedvd.
The memtest86 boot option is available in extra boot images to test local RAM
for errors.

This lists the possible command line options that can be used to tweak the boot
process of this DVD. This lists the Gentoo-specific options, along with a few
options that are built-in to the kernel, but that have been proven very useful
to our users.  Also, all options that start with "do" have a "no" inverse, that
does the opposite.  For example, "doscsi" enables SCSI support in the initial
ramdisk boot, while "noscsi" disables it.

To list the options, please press keys from F3 through F10.

<F3> Hardware (Page 1)
<F4> Hardware (Page 2)
<F5> Hardware (Page 3)
<F6> Volume Management
<F7> Misc boot options
<F8> Extra boot images
<F9> GentooX Features
<F10> Accessibility options
